# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83b5876390c9e6712e8b66a14bcdbf0d549e6a48a3d6ad03ed6458cf59379e74b228ed9b3c5c1c31f7359fcea3bd2590dd8a9a73854990488f08fe4679218966

test:
  secret_key_base: 9550ddcbc61dc305ac509c87936c89093a9f8ab0c6f184216e6bac63cb54eb793bdb9c43158a086a7c0bd40ca617020afea52b6a4e8e8969a43bd560aaca63b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
